app:
  name: Scumbag
  debug: true
web:
  host: ""
  port: 4200
transcoding:
  rpc_listen: ":7100"
storage:
  driver: local # local|MinIO|ceph
  workdir: var/workdir

  local:
    mount: var/storage

  minio:
    endpoint: play.min.io
    access_key_id: Q3AM3UQ867SPQQA43P2F
    secret_access_key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    ssl: true

database:
  # sqlite|mysql
  driver: mysql
  # dsn: var/app.database
  dsn: root:123456@tcp(127.0.0.1:3306)/scumbag?charset=utf8mb4&parseTime=True&loc=Local
logging:
  file: var/logs/app.log